### ISSUE TITLE
DesignSystem개발

### ISSUE THREAD

**Issue by kim-jiha95** [potenday401/Popin#15]
[DesignSystem](https://www.notion.so/daisycom/179cfb2851a04d1b81aeb5aeee696a69?v=da2baf2880bf43a9b8df6b30658dab84&pvs=4) 을 개발합니다
- [x] Color
- [x] Button
- [x] InputField
- [x] Checkbox
- [ ] Tag
- [x] NavigationBar (AppBar)
- [x] VerificationCodeInput (인증번호)
- [ ] SegmentedControl

**Comment by cskime** [comment]
- Button component는 아직 일관된 스타일이 없어 보이고, 실제 화면에서도 잘 사용되지 않아 보임
- 한 가지 종류만 우선 개발하고, 다른 style은 디자인이 정리된 이후 필요할 때 추가 구현
- 아래 사항을 고려해야 함
  - Size: xlarge, large, small, xsmall
  - Primary, secondary : 각 size별로 primary, secondary color에 일관성이 없으므로 확인 필요
